name: CI

on:
  workflow_dispatch:
  push:
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: danvsilva/actions-python/lint@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
